### ISSUE TITLE
Traduire les instructions pour utiliser la clé USB de VVV

### ISSUE THREAD

**Issue by imath** [WordCampParis/contribuer-a-wordpress#21]
En préparant le 4e atelier, j'ai créé une clé USB avec VVV dessus en utilisant le script de Tom : https://github.com/Varying-Vagrant-Vagrants/CD-USB-Generator. À l'issue du processus, ce [fichier HTML](https://github.com/Varying-Vagrant-Vagrants/CD-USB-Generator/blob/master/resources/instructions.html) est ajouté à la racine du dossier `build` (celui dont le contenu est à copier dans la clé USB). En prévision de la journée de contribution du 24/04, ça serait un + si on pouvait inclure une version française.

**Comment by truchot** [comment]
Est-il indispensable d'utiliser VVV pour la journée de contribution au WordCamp Paris ?

**Comment by audrasjb** [comment]
Non ce n'est pas indispensable, mais fortement recommandé pour contribuer à WordPress en général. Mais il est possible de fonctionner avec d'autres outils comme MAMP, c'est juste que la procédure de test/build est plus laborieuse.

**Comment by truchot** [comment]
Ça marche je vais me faire une installation de Vagrant alors, merci !
